_target_: 'kitchen_eval.EvaluationApp'

# Environment
agent:
  _target_: "src.clients.agents.octo_client.OctoClient"
  ensemble: false

# agent:
#   _target_: "src.clients.agents.crossformer_client.CrossformerClient"

env:
  _target_: "src.clients.envs.rr_client.RREnvClient"
  host: "127.0.0.1"
  port: 6060

# Tasks
task_map:
  _target_: src.kitchen.map_task
  _partial_: True
# task_transforms:
#   single_tasks:
#     repeat: 2
tasks: # TODO Update tasks
  # - name: "open_oven"
  #   subtasks:
  #     - 'open_oven'
  # - name: "close_oven"
  #   subtasks:
  #     - 'close_oven'
  # - name: "open_microwave"
  #   subtasks:
  #     - 'open_microwave'
  # - name: "close_microwave"
  #   subtasks:
  #     - 'close_microwave'
  # - name: "banana_from_right_stove_to_sink"
  #   subtasks:
  #     - 'banana_from_right_stove_to_sink'
  # - name: "banana_from_sink_to_right_stove"
  #   subtasks:
  #     - 'banana_from_sink_to_right_stove'
  # - name: "pot_from_right_stove_to_sink"
  #   subtasks:
  #     - 'pot_from_right_stove_to_sink'
  # - name: "pot_from_sink_to_right_stove"
  #   subtasks:
  #     - 'pot_from_sink_to_right_stove'
  - 'pot_from_right_stove_to_sink'
  - 'banana_from_right_stove_to_sink'
  - 'open_microwave'
  - 'close_microwave'
  - 'open_oven'
  - 'open_ice'
  - 'push_toaster_lever'
  - 'pull_oven_tray'
  - 'close_ice'
  - 'banana_from_right_stove_to_oven_tray'
  - 'pot_from_sink_to_left_stove'
  - 'pot_from_left_to_right_stove'
  - 'banana_from_tray_to_right_stove'
  - 'close_oven'
  - 'pot_from_right_to_left_stove'
  - 'push_oven_tray'
  - 'banana_from_sink_to_right_stove'
  - 'pot_from_left_stove_to_sink'
  - 'pickup_toast_and_put_to_sink'
  - 'pot_from_sink_to_right_stove'